"""schema initial

Revision ID: 5ae5806a2359
Revises: 
Create Date: 2026-10-08 11:40:38.911609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae5806a2359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('poids', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('poids BETWEEN 1 AND 5', name='ck_critere_poids'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('poste', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('telephone', sa.String(length=40), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employes_matricule'), ['matricule'], unique=True)
        batch_op.create_index(batch_op.f('ix_employes_nom'), ['nom'], unique=False)

    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['employes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('localisation', sa.String(length=160), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['employes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('doit_changer_mdp', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('echecs_connexion', sa.Integer(), nullable=False),
    sa.Column('bloque_jusqua', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('rh','direction','collaborateur')", name='ck_utilisateur_role'),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employe_id')
    )
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateurs_email'), ['email'], unique=True)

    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('evaluateur_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(departement_id IS NULL) <> (projet_id IS NULL)', name='ck_affectation_un_contexte'),
    sa.CheckConstraint('evaluateur_id IS NULL OR evaluateur_id <> employe_id', name='ck_affectation_pas_auto'),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluateur_id'], ['employes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affectations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affectations_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affectations_employe_id'), ['employe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affectations_evaluateur_id'), ['evaluateur_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affectations_projet_id'), ['projet_id'], unique=False)

    op.create_table('imports_brouillons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('source_nom', sa.String(length=200), nullable=True),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('cible', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_actions_utilisateur_id'), ['utilisateur_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affectation_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=12), nullable=False),
    sa.Column('note_globale', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('axes_amelioration', sa.Text(), nullable=True),
    sa.Column('rouverte', sa.Boolean(), nullable=False),
    sa.Column('soumise_le', sa.DateTime(), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('evaluateur_id', sa.Integer(), nullable=True),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("statut IN ('brouillon','soumise')", name='ck_evaluation_statut'),
    sa.CheckConstraint('mois BETWEEN 1 AND 12', name='ck_evaluation_mois'),
    sa.ForeignKeyConstraint(['affectation_id'], ['affectations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluateur_id'], ['employes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affectation_id', 'annee', 'mois', name='uq_evaluation_periode')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_dept', ['departement_id', 'annee'], unique=False)
        batch_op.create_index('ix_evaluation_employe_periode', ['employe_id', 'annee', 'mois'], unique=False)
        batch_op.create_index('ix_evaluation_periode', ['annee', 'mois'], unique=False)
        batch_op.create_index('ix_evaluation_projet', ['projet_id', 'annee'], unique=False)

    op.create_table('evaluation_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('critere_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('poids', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.CheckConstraint('note BETWEEN 0 AND 100', name='ck_note_bornes'),
    sa.ForeignKeyConstraint(['critere_id'], ['criteres.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'critere_id', name='uq_note_critere')
    )
    with op.batch_alter_table('evaluation_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_notes_evaluation_id'), ['evaluation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_notes_evaluation_id'))

    op.drop_table('evaluation_notes')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_projet')
        batch_op.drop_index('ix_evaluation_periode')
        batch_op.drop_index('ix_evaluation_employe_periode')
        batch_op.drop_index('ix_evaluation_dept')

    op.drop_table('evaluations')
    with op.batch_alter_table('journal_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_actions_utilisateur_id'))
        batch_op.drop_index(batch_op.f('ix_journal_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_journal_actions_action'))

    op.drop_table('journal_actions')
    op.drop_table('imports_brouillons')
    with op.batch_alter_table('affectations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affectations_projet_id'))
        batch_op.drop_index(batch_op.f('ix_affectations_evaluateur_id'))
        batch_op.drop_index(batch_op.f('ix_affectations_employe_id'))
        batch_op.drop_index(batch_op.f('ix_affectations_departement_id'))

    op.drop_table('affectations')
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateurs_email'))

    op.drop_table('utilisateurs')
    op.drop_table('projets')
    op.drop_table('departements')
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employes_nom'))
        batch_op.drop_index(batch_op.f('ix_employes_matricule'))

    op.drop_table('employes')
    op.drop_table('criteres')
    # ### end Alembic commands ###
